# Tabela de massas monoisotópicas padrão Rosalind
TABELA_MASSAS = {
    'A': 71.03711, 'C': 103.00919, 'D': 115.02694, 'E': 129.04259,
    'F': 147.06841, 'G': 57.02146, 'H': 137.05891, 'I': 113.08406,
    'K': 128.09496, 'L': 113.08406, 'M': 131.04049, 'N': 114.04293,
    'P': 97.05276, 'Q': 128.05858, 'R': 156.10111, 'S': 87.03203,
    'T': 101.04768, 'V': 99.06535, 'W': 186.07931, 'Y': 163.06333
}

def calcular_massa(sequencia_bruta):
    # O .strip() limpa espaços e quebras de linha invisíveis
    proteina = sequencia_bruta.strip()
    
    total = 0.0
    for aminoacido in proteina:
        if aminoacido in TABELA_MASSAS:
            total += TABELA_MASSAS[aminoacido]
    
    return round(total, 3)

# --- ÁREA DE TESTE ---
# Cole sua sequência entre as aspas simples abaixo
seq_input = 'YGGRHACVPKFEMPMFAGKTIECFVDHVAPLGYSINAAKCNIVYSEIYLDVTAWGITQIQAVVELIDFRDCFHACVPMPWTGWMQGRKGKRKNEYMTSPKFTNAEINRHDNRCLHSGGTWHARYSQPACKFPALLPRNYDCPNHIQRFSDVYERYTALSMGSIYYDFSEDQHTEGFLGDIRLCPELEDAGKQTKGKKNYVPRDTSTLIQHNKEGKKCWCAFNDKINVETKTMFVWHRVDFMKELANECTKRQWQHSCYLKECCRNACCYTAICVNCMAVTQNVCYDCLWANIGGCVIPPKHCNMDVLADKRIYRVNAKPGIRRSDYSSYWWEEIEFLVWQWVNPQNCRQPLCVQKWAFRCWINTLQQVQTIDPQVIPHIEAYVNTYKWTHQPSWYCPLSKHCDGLETAANVPCIIINKPFAPFGSGDYHIWGNTDCMTENDQMLAIGGTGQTSDLCWYHWPVTVWVKVWVMRMETHCSVELFKWSLLNVECSAHQFTHKEEGMEDHGAIGQHSGGWCDDNDEYLQTWLKSQCICWRPTPLVATSPNKADNLDIKGPRPQPCAMAGRGEDCQSRHKPDAASGNPARRQYPKQFGKQVFAFTAPQAAENKTWRFVAFIDWWDLIMENFQVGPVINWCRMVLSCHETYQGPGWRDYGLDDINVAWPSIACKYAQSHWLAKLLRKSMGAWGQPAIFSHQWLPGYVTPSFVYDPTSRDPIQIEHVMASEIFSDKWEGPDVKQITGQMAQMNYGLWFAQIPEDWDHYLQEIAPKGVTPGIDCWRKNNMMHSPYGYFQTAQMQGNTTAHSMFAEANAYFGTKDCMPDGDMYPPGVMLDMLQIKRTAGVLYILPEYEDKAIKEDIPLYVQGLTIHVGPSIDTYADWKYKNAFRHNKCWQKVYQFPSTDFTADVLGHWDPVQHVWWPRPFWGFDTCNLDHWSWQAWHEVFAFSNVHDRCY'

resultado_final = calcular_massa(seq_input)

print("-" * 30)
print(f"RESULTADO: {resultado_final}")
print("-" * 30)