s1 = 'GCGCTGATACGGCTTCGCGCATCCACAATACGGAGGTGAGTTCAAGTCTGGGCTGTAAGGTGTGTAAAGGTTCACGAACGGCGTGGTGACGCCTAGGTCTCTCAGGATGATTCGAGTAATACGACCCACTCACGGACAGTGTGCAACACTCTCCGGGGGGCGTACATACGGGTTTAGTGGGAAACGCGTCTGGACTATTGTCCTTATATCCGTCGTTACAGCTTCGAAAGGCGATCTGCACTGTGTGCACAAAAGAACACTACCAAACGAGCCCTAAGCAGAGAACATTTGAAGGAAAAATTATAAGTTCACTTCCGCCAGCTGCGCTAGCTCCGCGAACTTCAGGGACCGCTCAGCGTCCTCGCAGGCGCCAACACGAGGTTCCCGATCAAGAATAGTTTTCTGGGCCCGGGCCTATTCCCCAGATATAGCACGAATCCTGTATGCAGGGCAAAGGCCCTCGCGGATACATCCGGCCCCTATAAGGATATTGCGACTTCGTATGGGAATTCAGCTTCCGGAATAACCCGGGGTACTGGTACAACTTAACTGGACTGTGTATTAGCGTGTCACCAAGCTTCAACAAAATCTGGACAACATGGTTTAGAATGAGCACTGAGTTAGAGAAAATGAACAACTTTGTGTGCTACCGTAGCCAGGACCAGCATAGGGAATTATGAGTCTGCGCCGGCGACTAACTACTCCATTAATCCCGTTCAACCATATGCCACGTAATGCCGAAATGAATCAAGACCGTCCGATGAAAATCCTGACAGAAGTAGCTGTCCGCGTGTGGCTAGTGATCGCGCACAACGTGAGCGATACAAAGCCTAGTCAGAGGATCCAAAAGTGGTGACCGATTCGTCCGGCAACCCCAGCCTTATGGACCGGTGCACCTGTAAGAAGCGTAATACCAGCATCCTTTACCTCTCAG'
s2 = 'CAGCTGCTATGTGAGCTATGCAGCGCGATGGGGCGGGTCATAGCGAAGGATTCAGAAAGGTAGGAAACCGTAGACGTACGGCGTGGCGGCTGTTATGACTCGTAGTCTACTGCGTGACATCAGACACAGTTACGAATCGTCCGTCAGGCTTCGACGGAATGTTGTATTACGCGGCAGTAGAGGCCGCGCCGAGGCTACGTTGCTTAAGTTTGGACTTCCCGCCACGTGGCGGCCTCAATAGGCATGCAACCATTGCCCTCTACTATTTGAGCGCTAGACAACGCACGATTGGAGAAAAACTAGTGGCGCTAATTTCACCGTCTGCACTCGATTCGTGGAAACCCCCGATGAATGTCCGTTATCGCCATGCCACACTATGCGCGTCCAACTGTTGATAGTGTTATGCGCCCATGACGAAACGCCGCATATAGCAATGAAACCATACGCAGCGAAAGGGCCGCCCAGGGGACGTCGAGCCAGAATACTTATCCGCCGAAGACGTGCGGCAGTGTTAATTTGTGCTTCAACCGTTCTGCAAGGTCCTTCTAATCGGATGGTGTAGTGACGTACCTGTAAAATATTATATGTTGATGCCAAAAAGATTTACTGAGATTACCGCGTTTTGGATATTGACCAAGATTTGGTCTCGTCGGCGCATTATTCACTAGATTGAAGCAGGAATTTTCGAATGCCATTGAGTGGACCACTGCTACAATGAAATCCTATGAACAGTAACGCCGCTAGGCGTCCCGAACGTCCGACATAATGGAATACACAACCAGATCTCTGCCTTCGACTGGCTTTAGAACTAACACTGCGGGCTATCCGGTAAAGGCCGAGGATCGAGAGGTGCTTCTCGAATGGCAAGCCGCTCCTAGTTCGCAAGCCCCCCGAACCTGAAAGAACATGAGCGGCGGATACCATAGTCGTGTAG'

def hamming_distance(seq1, seq2): #Definimos uma função para que possamos reutilizar esse código em qualquer sequência, não apenas nas do exemplo.
    distancia = 0 # Iniciamos um contador do 0

    for base1, base2 in zip(s1, s2):
    # O 'zip' cria pares: (s[0], t[0]), (s[1], t[1])... Ela percorre as duas strings ao mesmo tempo, sendo muito mais rápida do que os índices numéricos
    # 'base1' recebe a letra da primeira string(s1), 'base2' a da segunda(s2)
        if base1 != base2:
            distancia += 1
    return distancia

print(hamming_distance(s1, s2))

'''
EXPLICAÇÃO TÉCNICA (HAMM):
1. ENTRADA: Duas strings de DNA de mesmo comprimento.
2. MÉTODO: Iteração paralela usando zip() para comparar bases correspondentes.
3. CONTAGEM: Incremento de variável sempre que a base de 's1' for diferente da base de 's2'.
4. RESULTADO: O valor final representa a Distância de Hamming, ou seja, o número mínimo de mutações pontuais entre as sequências.
'''

'''
DICA DE PERFORMANCE:
Preferimos zip(seq1, seq2) ao inver de range(len(s)) porque:
    1. Legibilidade: O código foca nos dados (letras) e não nos índices (números).
    2. Eficiência: O zip é um iterador, processando par a par sem sobrecarregar a memória.
    3. Segurança: Evita erros de 'index out of range' se as strings tiverem tamanhos diferentes (o zip para na menor).
'''

